FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

COPY backend_games/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY backend_games ${LAMBDA_TASK_ROOT}/backend_games

CMD ["backend_games.handler.handler"]
